# Generated by Django 4.2.6 on 2023-10-08 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MI', 'Miami'), ('LA', 'LosAngeles'), ('NY', 'NewYork'), ('MS', 'Moscow'), ('SP', 'SaintPetersburg'), ('PA', 'Paris'), ('GR', 'Greece'), ('IT', 'Italy')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('RUSSIAN FEDERATION', 'RUSSIAN FEDERATION'), ('USA', 'USA'), ('FRANCE', 'FRANCE'), ('GREEK REPUBLIC', 'GREEK REPUBLIC'), ('ITALY', 'ITALY')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
